### ISSUE TITLE
Ability to disable "View bnd apps" option

### ISSUE THREAD

**Issue by Fei1Yang** [cliuff/boundo#1]
![Screenshot_20210427-030921253](https://user-images.githubusercontent.com/48410544/116179156-bef46300-a70e-11eb-9c1d-1b86af6fd1a4.jpg)
It's really annoying to have this option avaliable everywhere.

**Comment by cliuff** [comment]
@Fei1Yang the option is available at: bottom navigation "more" -> Instant -> scroll to the "more" section -> View boundo apps
