### ISSUE TITLE
"Consuming Mode" ?

### ISSUE THREAD

**Issue by AdamKane41** [cliuff/boundo#4]
Hello,
In the "About" section when triple-taping on the heart icon it Toggles ON and OFF "Consuming Mode" . What is "Consuming Mode" and what does it do? My guess would be that it's to activate some Debugging features but I really dont know. Thank you for letting me know, good stuff! :)

Peace

**Comment by cliuff** [comment]
Consuming mode will show more options that are hidden by default for various reasons, and language switching was one of them. Since there are no hidden features now, turning it on does not do anything useful.
